### ISSUE TITLE
Clicking on '≡' shows only white screen on mobile devices

### ISSUE THREAD

**Issue by maulikpareek** [nakul1710/bookbuddy.co.in#1]
Once we click on '≡' present at top right side of mobile devices, it leads to a blank white space with no options to see navigation bar tabs like 'Home', 'Contacts' etc. 

https://github.com/nakul1710/bookbuddy.co.in/assets/144589199/81ed0965-45c4-4b00-9e90-68c41bf35575

Fix it 👍

**Comment by nakul1710** [comment]
no it is not website booksbuddy.co.in is my website there a slits difference b/w book and books
